#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7  

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Telegram-desktop desktop='^6' state=floating follow=on
bspc rule -a code desktop='^1'
bspc rule -a brave desktop='^2'
bspc rule -a Chromium desktop='^2'

exec ~/.config/polybar/launch.sh --hack &
exec picom &
exec feh --bg-scale ~/Imágenes/wallpapers/krimkerre_4_endy_neon.jpg &
exec nm-applet &
exec xsetroot -cursor_name left_ptr & 
